### ISSUE TITLE
Support for Nested Structures in OpenAPI definitions

### ISSUE THREAD

**Issue by chrised** [dikhan/terraform-provider-openapi#108]
## Is your feature request related to a problem?
We would like support for Nested Structures in our API Spec. This is currently supported by OpenAPI, but the plugin lacks support for it.
As far as I'm aware, this is possible within Terraform, but requires some workarounds until the 0.12 API/SDK takes over fully. See: https://github.com/hashicorp/terraform/issues/21217

## Acceptance criteria
Support for nested structures in OpenAPI definitions.

## Describe alternatives you've considered
We currently have this implemented at the top-level as multiple fields, but doesn't provide us any forward compatibility if we were to add additional *similar* structures, which abide by different names.

## Additional context
Example structure for compatibility:
```
definitions:
  TopLevel:
    type: object
    required:
      - name
      - subobject
    properties:
      name:
      subobject:
        type: object
        required: 
          - id
       properties:
         id:
           type: string
         region:
           type: string
           enum:
            - us-east-1
            - us-west-2
            - eu-west-1
            - eu-central-1
            - ca-central-1
```

## Checklist

**Don't forget to go through the checklist to make sure the issue is created properly**:

- [x] I have added a corresponding label (feature request/bug/etc) to the issue (right side menu)
- [x] I have added this issue to the 'API Terraform Provider' GitHub project (right side menu)
