### ISSUE TITLE
Support for complex objects

### ISSUE THREAD

**Issue by dikhan** [dikhan/terraform-provider-openapi#147]
## Is your feature request related to a problem?

The current version of Terraform SDK, at the time of writing terraform <= 0.12.7, has a limitation in the helper/schema SDK where as per the [documentation for Schema Elem field](https://github.com/hashicorp/terraform/blob/v0.12.7/helper/schema/schema.go#L169), 
TypeMap does not support complex object types:

- [Issue 22511](https://github.com/hashicorp/terraform/issues/22511): Objects that contain properties with different types (e,g: string, integer, etc) and configurations (e,g: some of them being computed)
- [Issue 21217](https://github.com/hashicorp/terraform/issues/21217): Objects that contain nested objects

The alternative suggested by Hashi Terraform maintainers is to use a workaround whereby configuring the terraform schema for complex objects  using a TypeList attribute with MaxItems: 1 set and its Elem set to a nested *schema.Resource removes the limitation enabling complex objects to be set up properly and ensuring internal terraform behaviour works as expected.

## Describe the solution you'd like

The OpenAPI Terraform provider supports the above as follows:

- Scenario 1: Objects that contain properties with different types (e,g: string, integer, etc) and configurations (e,g: some of them being computed)

Swagger representation:

````
definitions:
  ContentDeliveryNetworkV1:
    type: "object"
    properties:
      id:
        type: "string"
        readOnly: true
      complex_object: # this object is considered complex because it contains properties that have different configurations (some are readOnly, aka computed)
        type: "object"
        x-terraform-complex-object-legacy-config: true
        properties:
          account:
            type: string
          computed_property:
            type: string
            readOnly: true
````

Corresponding terraform configuration representation:

````
resource "swaggercodegen_cdn_v1" "my_cdn" {
  object_property_block {
    account = "my_account"
  }
}
````

As you can see the above complex object definition contains the extension ```x-terraform-complex-object-legacy-config:``` enabled (value set to true), which means that the service provider acknowledges that the behaviour expected from the OpenAPI Terraform provider plugin is the workaround suggested above.

Note: This extension is needed to be able to let the OpenAPI plugin know that this behaviour is desired. Otherwise, the OpenAPI plugin will configure the terraform schema without the workaround configuring the terraform schema property with a type TypeMap which in the case of complex types will result into [unpredicted behaviour (https://github.com/hashicorp/terraform/issues/22511#issuecomment-522609116). This extension has been added to safe guard from future Terraform releases and simplify support for proper complex types without workaround or extra extension when the Terraform SDK supports it. 

- Scenario 2: Objects that contain nested objects

Swagger representation:

````
definitions:
  ContentDeliveryNetworkV1:
    type: "object"
    properties:
      id:
        type: "string"
        readOnly: true
      object_with_nested_objects:
        type: "object"
        properties:
          name:
            type: "string"
            readOnly: true
          object_property:
            type: "object" # nested object
            x-terraform-complex-object-legacy-config: true
            properties:
              account:
                type: string
            computed_property:
              type: string
              readOnly: true
````

Corresponding terraform configuration representation:

````
resource "swaggercodegen_cdn_v1" "my_cdn" {
  object_with_nested_objects {
    name = "dani"
    object_property {
      account = "something"
    }
  }
}
````

Due to the nature of these objects, even though they are also considered complex objects, they do not require the extension ```x-terraform-complex-object-legacy-config``` to be present and enabled to trigger the [workaround configuration](https://github.com/hashicorp/terraform/issues/21217#issuecomment-489699737) schema using TypeList with MaxItems equal to 1 and its Elem set to a nested *schema.Resource. Since this was the only way to set up these type of complex objects with the current limitation of Terraform SDK, another extension was not required and therefore the OpenAPI provider uses the legacy Terraform workaround for configuring objects with nested objects as the default behaviour.

## Acceptance criteria

```gherkin
Scenario: 
Given the below Swagger Model definition
When the below Terraform configuration is executed running terraform apply
Then the state file produced should match the expected one (as specified below) and any subsequent terraform plans should finalize with a clean state and no diffs whatsoever.
```

- Swagger Model definition:

````
  ContentDeliveryNetworkV1:
    type: "object"
    required:
      - label
    properties:
      id:
        type: "string"
        readOnly: true
      label:
        type: "string"
      computed_property:
        type: "string"
        readOnly: true
      object_property_block: 
        type: "object"
        x-terraform-complex-object-legacy-config: true
        properties:
          account:
            type: string
          object_read_only_property:
            type: string
            readOnly: true
````

- Terraform configuration

````
		resource "openapi_cdn_v1" "my_cdn" {
		  label = "my label"
		  object_property_block {
		   account = "my_account"
		  }
		}
````

- Expected terraform state:

````
(*terraform.State)(0xc000b06060)(openapi_cdn_v1.my_cdn:
  ID = 42
  provider = provider.openapi
  computed_property = some auto-generated value
  label = CDN #42
  object_property_block.# = 1
  object_property_block.0.account = my_account
  object_property_block.0.object_read_only_property = some computed value for object read only
openapi_cdn_v1_firewalls_v1.my_cdn_firewall_v1:
  ID = 1337
  provider = provider.openapi
  cdn_v1_id = 42
  label = FW #1337

  Dependencies:
    openapi_cdn_v1.my_cdn)
````

The expected internal representation of the object property containing the aforementioned extension. As you can see the Type is TypeList, Elem is *schema.Resource with MaxItems: (int) 1 and the Elem schema contains the expected properties as defined in the swagger file.

````
 (string) (len=21) "object_property_block": (*schema.Schema)(0xc0002a2300)({
  Type: (schema.ValueType) TypeList,
  ConfigMode: (schema.SchemaConfigMode) 0,
  Optional: (bool) true,
  Required: (bool) false,
  DiffSuppressFunc: (schema.SchemaDiffSuppressFunc) <nil>,
  Default: (interface {}) <nil>,
  DefaultFunc: (schema.SchemaDefaultFunc) <nil>,
  Description: (string) "",
  InputDefault: (string) "",
  Computed: (bool) false,
  ForceNew: (bool) false,
  StateFunc: (schema.SchemaStateFunc) <nil>,
  Elem: (*schema.Resource)(0xc00071e100)({
   Schema: (map[string]*schema.Schema) (len=2) {
    (string) (len=25) "object_read_only_property": (*schema.Schema)(0xc0002a2400)({
     Type: (schema.ValueType) TypeString,
     ConfigMode: (schema.SchemaConfigMode) 0,
     Optional: (bool) true,
     Required: (bool) false,
     DiffSuppressFunc: (schema.SchemaDiffSuppressFunc) <nil>,
     Default: (interface {}) <nil>,
     DefaultFunc: (schema.SchemaDefaultFunc) <nil>,
     Description: (string) "",
     InputDefault: (string) "",
     Computed: (bool) true,
     ForceNew: (bool) false,
     StateFunc: (schema.SchemaStateFunc) <nil>,
     Elem: (interface {}) <nil>,
     MaxItems: (int) 0,
     MinItems: (int) 0,
     PromoteSingle: (bool) false,
     Set: (schema.SchemaSetFunc) <nil>,
     ComputedWhen: ([]string) <nil>,
     ConflictsWith: ([]string) <nil>,
     Deprecated: (string) "",
     Removed: (string) "",
     ValidateFunc: (schema.SchemaValidateFunc) 0x215f060,
     Sensitive: (bool) false
    }),
    (string) (len=7) "account": (*schema.Schema)(0xc0002a2500)({
     Type: (schema.ValueType) TypeString,
     ConfigMode: (schema.SchemaConfigMode) 0,
     Optional: (bool) true,
     Required: (bool) false,
     DiffSuppressFunc: (schema.SchemaDiffSuppressFunc) <nil>,
     Default: (interface {}) <nil>,
     DefaultFunc: (schema.SchemaDefaultFunc) <nil>,
     Description: (string) "",
     InputDefault: (string) "",
     Computed: (bool) false,
     ForceNew: (bool) false,
     StateFunc: (schema.SchemaStateFunc) <nil>,
     Elem: (interface {}) <nil>,
     MaxItems: (int) 0,
     MinItems: (int) 0,
     PromoteSingle: (bool) false,
     Set: (schema.SchemaSetFunc) <nil>,
     ComputedWhen: ([]string) <nil>,
     ConflictsWith: ([]string) <nil>,
     Deprecated: (string) "",
     Removed: (string) "",
     ValidateFunc: (schema.SchemaValidateFunc) 0x215f060,
     Sensitive: (bool) false
    })
   },
   SchemaVersion: (int) 0,
   MigrateState: (schema.StateMigrateFunc) <nil>,
   StateUpgraders: ([]schema.StateUpgrader) <nil>,
   Create: (schema.CreateFunc) <nil>,
   Read: (schema.ReadFunc) <nil>,
   Update: (schema.UpdateFunc) <nil>,
   Delete: (schema.DeleteFunc) <nil>,
   Exists: (schema.ExistsFunc) <nil>,
   CustomizeDiff: (schema.CustomizeDiffFunc) <nil>,
   Importer: (*schema.ResourceImporter)(<nil>),
   DeprecationMessage: (string) "",
   Timeouts: (*schema.ResourceTimeout)(<nil>)
  }),
  MaxItems: (int) 1,
  MinItems: (int) 0,
  PromoteSingle: (bool) false,
  Set: (schema.SchemaSetFunc) <nil>,
  ComputedWhen: ([]string) <nil>,
  ConflictsWith: ([]string) <nil>,
  Deprecated: (string) "",
  Removed: (string) "",
  ValidateFunc: (schema.SchemaValidateFunc) <nil>,
  Sensitive: (bool) false
 })
````

## Checklist

**Don't forget to go through the checklist to make sure the issue is created properly**:

- [x] I have added a corresponding label (feature request/bug/etc) to the issue (right side menu)
- [x] I have added this issue to the 'API Terraform Provider' GitHub project (right side menu)
