### ISSUE TITLE
immutable properties where the value has not changed not working properly

### ISSUE THREAD

**Issue by dikhan** [dikhan/terraform-provider-openapi#159]
## Describe the bug

Terraform complains for immutable property even though swagger is marked with default value

````
Error: property network_prefix_length is immutable and therefore can not be updated. 
````

## To Reproduce

Given a terraform compatible resources that uses the following swagger as the resource model definition:

````
definitions:
  Subnet:
    required:
    - vpc_uuid
    type: object
    properties:
      network_prefix_length:
        default: 27
        type: integer
        x-terraform-immutable: true
      vpc_uuid:
        title: Vpc uuid
        type: string
        x-terraform-immutable: true
````

And the following corresponding terraform configuration:
````
resource "openapi_subnets" "my_subnet" {
  vpc_uuid = "some_vpc_uuid"
}

````

Steps to reproduce the behaviour:
1. Run terraform apply
2. The resource will be created with the right state containing the network_prefix_length and the vpc_uuid
3. Subsequent plans will result into diffs saying that the network_prefix_length value is immutable even though the value has not changed.

## Expected behaviour

No diffs should happen if the value of the immutable property has not changed.

## Additional context

When comparing the state from remote API with the local changes, the structs marshalled from the API response JSON was treating all ints as floats and when the comparison with the local state value was performed, the check was detecting a diff due to type differences even though the value was the same:

Example: immutable field updated [updatedValue: %!s(int=26); actual: %!s(float64=26)]

### Checklist

**Don't forget to go through the checklist to make sure the issue is created properly**:

- [x] I have added a corresponding label (feature request/bug/etc) to the issue (right side menu)
- [x] I have added this issue to the 'API Terraform Provider' GitHub project (right side menu)
