### ISSUE TITLE
x-terraform-ignore-order does not appear to work

### ISSUE THREAD

**Issue by arjunrajinstaclustr** [dikhan/terraform-provider-openapi#326]
## Describe the bug
Using v2.2.0 of the plugin, the `x-terraform-ignore-order: true` property does not appear to ignore ordering differences between the terraform state and the API response.

## To Reproduce
Use `x-terraform-ignore-order: true` on an array type property (see example below)

## Expected behaviour
Differences in ordering between the API's response and terraform state are ignored.

Example:
```
definitions:
    Widget:
        title: Root Type for Widget
        description: 'A very simple, generic data type.'
        required:
            - dependencies
        type: object
        properties:
            id:
                description: The id of the widget.
                type: string
                readOnly: true
            dependencies:
                description: The dependencies of the widget.
                type: array
                x-terraform-ignore-order: true
                items:
                    type: string
```

Looking at the debug logs, I can see that the `IgnoreItemsOrder` is marked as `true` as expected -

```
   {
       "Name": "dependencies",
       "PreferredName": "",
      "Type": "list",
      "ArrayItemsType": "string",
       "Description": "",
      "IgnoreItemsOrder": true,
```

However `terraform plan` still shows a diff - 

```
  # mytest_widget.example will be updated in-place
  ~ resource "mytest_widget" "example" {
        id                            = "c80c0b1d-2a51-4ce2-95c2-075afac3306c"
      ~ dependencies      = [
          - "dep3",
            "dep1",
            "dep2",
          + "dep3",
        ]
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Checklist (for admin only)

**Don't forget to go through the checklist to make sure the issue is created properly**:

- [ ] I have added a corresponding label (bug) to the issue (right side menu)
- [ ] I have added this issue to the 'API Terraform Provider' GitHub project (right side menu)
