### ISSUE TITLE
Enable external plugin configuration

### ISSUE THREAD

**Issue by dikhan** [dikhan/terraform-provider-openapi#34]
Please check one of the options below and follow the instructions: 

- [x] **Feature Request** fill out ['Feature Request'](#featureRequest) section and remove the rest
- [ ] **Bug Found** fill out ['Bug Found'](#bugFound) and remove the rest

*Please put an `x` (w/o heading/trailing white spaces) in the boxes that apply.*

### Checklist

**Don't forget to go through the checklist to make sure the issue is created properly**:

- [x] I have filled out the right section (feature request/bug) and added enough details.
- [x] I have added a corresponding label (feature request/bug) to the issue (right side menu)
- [x] I have added this issue to the 'API Terraform Provider' GitHub project (right side menu)

## <a name="featureRequest">Feature Request</a>

- What problem does it solve? Key benefits?
Currently, the only way to provide info to the provider is via environment variables such as OTF_VAR_<provider_name>_SWAGGER_URL and OTF_INSECURE_SKIP_VERIFY. When managing multiple service providers that end up using the same open api provider this becomes a hardle. Hence, the proposal of supporting a configuration file that the provider can read on startup and if present figure out service configuration based on the values set in the file.

Key benefits include: running terraform commands cleanly without having to pass specific env variables per service used and centralized configuration.

- Proposed solution?
An initial proposal would be to support a config file with the following specification:

````
version: '1'
  services:
    monitor:
      swagger-url: http://monitor-api.com/swagger.json
      insecure_skip_verify: true
    cdn:
      swagger-url: https://cdn-api.com/swagger.json
    vm:
      swagger-url: http://vm-api.com/swagger.json
    goa: 
      swagger-url: https://some-domain-where-swagger-is-served.com/swagger.yaml 
````

- Estimated time required? 2d

#### Acceptance criteria

What's required to consider this feature request complete? Please provide details:
