### ISSUE TITLE
Add support for headers 

### ISSUE THREAD

**Issue by dikhan** [dikhan/terraform-provider-openapi#37]
Please check one of the options below and follow the instructions: 

- [x] **Feature Request** fill out ['Feature Request'](#featureRequest) section and remove the rest
- [ ] **Bug Found** fill out ['Bug Found'](#bugFound) and remove the rest

*Please put an `x` (w/o heading/trailing white spaces) in the boxes that apply.*

### Checklist

**Don't forget to go through the checklist to make sure the issue is created properly**:

- [x] I have filled out the right section (feature request/bug) and added enough details.
- [x] I have added a corresponding label (feature request/bug) to the issue (right side menu)
- [x] I have added this issue to the 'API Terraform Provider' GitHub project (right side menu)

## <a name="featureRequest">Feature Request</a>

Currently, the only way to add headers to requests in the OpenAPI terraform provider is by setting apiKey security policies. Sometimes, this might not be desired and the ability to specify expected headers on a per operation basis would be preferable.

This story is about adding support for headers to be passed in as a parameter:

````
paths:
  /ping:
    get:
      summary: Checks if the server is alive.
      parameters:
        - in: header
          x-terraform-header: billing_token
          name: sl-billing-token
          type: string
          required: true
````

This would translate into a terraform provider configuration as follows:

````
provider "demo" {
  billing_token = "some value"
}
````

The reason why the extension is needed is because the header name might not necessarily be compliant with terraform field name convention (Field name may only contain lowercase alphanumeric characters & underscores.) and also the provider might just use a different name for configuration purposes so decoupling these two seems to be the right approach. On the terraform provider config side the field name use will be the one specified in the x-terraform-header

````
          x-terraform-header: billing_token
          name: sl-billing-token
````

#### Acceptance criteria

- Operations with header parameters would expect the value to come from the provider configuration. If the value is not present an error should be thrown.
- Operations that do not have the header param will not send the header value along with the request
