### ISSUE TITLE
Allow for provider properties to be configured from external files

### ISSUE THREAD

**Issue by dikhan** [dikhan/terraform-provider-openapi#76]
## Is your feature request related to a problem?
At the moment only supported ways to populate provider schema properties is either via inline configuration or environment variables. This feature request covers the case where users may have shared configuration files where they store, for example, their tokens and would liek to use those values for the provider schema.

## Describe the solution you'd like
The ideal solution would allow me to specify in the plugin configuration file not only configuration related to the plugin such as swagger file location and insecure skip verify but also schema property configuration. The schema property configuration would allow to configure all the properties exposed via the provider and be able to set default values. The default values could be set either inline or they could come from an external configuration file. Since the external config file could be formatted in many different ways, for now to reduce the scope I'd like support for 'raw' content as well as 'json' content and in case of the latter I'd like to be able to specify which specific key I would like to use as default value (perhaps using JsonPath syntax)

Example of potential design:

````
version: '1'
services:
  swaggercodegen:
    swagger-url: https://swaggercodegen-service-provider-api.com/swagger.yaml
    insecure_skip_verify: true
    schema_configuration:
    - schema_property_name: "apikey_auth"
      default_value: "apiKeyValue"
      schema_property_external_configuration:
        content_type: raw
        file: /Users/dikhanr/.terraform.d/plugins/swaggercodegen
````

## Acceptance criteria

- I am able to provide default values to my openapi provider via the external configuration file.
- I am able to provide default values to schema properties of the provider from external source files
  - raw: will get all the content of the file and assign it as the default value
  - json: will use the 'key_name' and use its value as the default value
- I am able to specify where the plugin configuration file is located, hence be able to override the default location ~/.terraform.d/plugins/terraform-provider-openapi.yaml
- The solution is cross platform

## Checklist

**Don't forget to go through the checklist to make sure the issue is created properly**:

- [x] I have added a corresponding label (feature request/bug/etc) to the issue (right side menu)
- [x] I have added this issue to the 'API Terraform Provider' GitHub project (right side menu)
