### ISSUE TITLE
Support for Bearer auth schema authentication for header and query apikey auth 

### ISSUE THREAD

**Issue by dikhan** [dikhan/terraform-provider-openapi#78]
## Is your feature request related to a problem?
Currently, I need to pass in the 'Bearer' schema keyword as part of the auth token when injecting the value into the provider. This leads to expose to the client information that the client should not really care about and also makes the injection more error prone if the client forgets to add the schema to the auth token.

Unfortunately, OpenAPI 2.0 spec does not have support for such schema auth and therefore can't leverage already supported directives from the spec. 

## Describe the solution you'd like
The solution proposed involves adding support for a new boolean extension 'x-terraform-authentication-scheme-bearer' only applicable to apiKey security definitions of type header/query which would allow the provider to identify specific bearer scheme or if not present or value is false to just use the regular header/query auth mechanism which follow the default behaviour.

- If the extension is present in an apiKey header authentication that would mean that the user will only have to pass in the JWT token as value for the provider's auth field and internally the provider will take care of adding the scheme to the value and the header name will follow the spec being 'Authorization'.

Example of enabling bearer auth to apiKey header auth:
````
securityDefinitions:
  apikey_auth:
    type: "apiKey"
    name: "Authorization" # even if the name is not present, with the extension enabled the provider will # use the header name as described in the bearer auth specification which is "Authorization"
    in: "header"
    x-terraform-authentication-scheme-bearer: true
```` 

- If the extension is present in an apiKey query authentication that would mean that the user will only have to pass in the JWT token as value for the provider's auth field and internally the provider will take care of setting up the URL with the auth bearer query parameters following the spec being the query name 'access_token'.

Example of enabling bearer auth to apiKey query auth:
````
securityDefinitions:
  apikey_auth:
    type: "apiKey"
    in: "query"
    x-terraform-authentication-scheme-bearer: true
```` 

## Acceptance criteria
What's required to consider this feature request complete?

- be able to attach the bearer extension to any apikey header/query schema definition and have the provider automatically handle the auth configuration internally
- in the case of apikey auth header bearer the expectation is that if the extension is present and enabled with value true, the final request made to the API (assuming the end point has that security scheme attach to it) the request will contain a header with name 'Authorization' and the value will include the Bearer scheme. 
- If the value already has the bearer scheme then 'Bearer' will not be added to avoid duplicates and also backwards compatibility for users that are already injecting the scheme to the value.
- in the case of apikey auth query bearer the expectation is that if the extension is present and enabled with value true, the final request made to the API (assuming the end point has that security scheme attach to it) the request will contain a query parameter with name 'access_token' and the value will be the value passed in by the user (with no extra information).

## Checklist

**Don't forget to go through the checklist to make sure the issue is created properly**:

- [x] I have added a corresponding label (feature request/bug/etc) to the issue (right side menu)
- [x] I have added this issue to the 'API Terraform Provider' GitHub project (right side menu)
