### ISSUE TITLE
Add support for URL Ref (specific element of the document stored on the different server)

### ISSUE THREAD

**Issue by dikhan** [dikhan/terraform-provider-openapi#93]
## Is your feature request related to a problem?

Currently only refs to definitions within the same swagger file is supported. This card adds support for external refs as described in the documentation:

https://swagger.io/docs/specification/using-ref/

More specifically this:

````
URL Reference – $ref: 'http://path/to/your/resource' Uses the whole document located on the different server.
- The specific element of the document stored on the different server – $ref: 'http://path/to/your/resource.json#myElement'
````

## Describe the solution you'd like

If a given operation has an external ref the provider would go ahead and fetch it and use that as the resource schema object.

````
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "http://path/to/your/resource.json#myElement"
````

## Acceptance criteria

- local refs should still be supported
- external refs, only applicable to refs with the body schema input param, will be retrieved in a similar fashion as to local refs.

## Checklist

**Don't forget to go through the checklist to make sure the issue is created properly**:

- [x] I have added a corresponding label (feature request/bug/etc) to the issue (right side menu)
- [x] I have added this issue to the 'API Terraform Provider' GitHub project (right side menu)
